#!/bin/bash
sudo su
cat << EOF > /etc/yum.repos.d/nginx.repo
[nginx]
name=nginx repo
baseurl=http://nginx.org/packages/centos/7/\$basearch/
gpgcheck=1
enabled=1
EOF
yum update -y
curl -O https://nginx.org/keys/nginx_signing.key
rpm --import https://nginx.org/keys/nginx_signing.key
sudo yum install nginx -y
